name: Create Release Tag

on:
  push:
    branches:
      - master

jobs:
  create-release-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read current version
        id: current_version
        run: echo "CURRENT_VERSION=$(cat VERSION)" >> "$GITHUB_OUTPUT"
      
      - name: Increment version
        id: increment_version
        run: |
          current_version=${{ steps.current_version.outputs.CURRENT_VERSION }}
          IFS='.' read -r -a version_parts <<< "${current_version#v}"
          major=${version_parts[0]}
          minor=${version_parts[1]}
          patch=${version_parts[2]}
          new_patch=$((patch + 1))
          new_version="v$major.$minor.$new_patch"
          echo "NEW_VERSION=${new_version}" >> "$GITHUB_OUTPUT"
          echo $new_version > VERSION

      - name: Commit and push updated VERSION
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add VERSION
          git commit -m "Increment version to ${{ steps.increment_version.outputs.NEW_VERSION }}"
          git push origin HEAD:release

      - name: Create and push the tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_version=${{ steps.increment_version.outputs.NEW_VERSION }}
          git tag $new_version
          git push origin $new_version

